name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # exemplu generic: rulezi scriptul tău
      - name: Set up environment
        run: |
          echo "Nothing to set up yet"

      - name: Run tests
        run: |
          echo "Run your tests here"
          # de ex: ./run_tests.sh
