name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # rulezi scriptul tau
      - name: Set up environment
        run: |
          echo "Nothing to set up yet"

      - name: Run tests
        run: |
          echo "Run your tests here"
          # ex: ./run_tests.sh
